
PREFIX wd: <http://wikidata.org/wiki/>
PREFIX wdt: <http://wikidata.org/prop/direct/>

SELECT ?sbj 
WHERE {
    ?sbj wdt:P19 wd:Q201007 .
    ?sbj wdt:P166 wd:Q37922 .
}


select var_sbj where brack_open var_sbj wdt_p19 
wd_q201007 sep_dot var_sbj wdt_p166 wd_q37922 
sep_dot brack_close



############################################################################################
################### QUESTION ANSWERING - DATASET DBNQA #####################################
############################################################################################

SELECT DISTINCT ?sbj WHERE {
    ?sbj dbp:placeOfBirth dbr:Stockholm .
    ?sbj rdf:type dbo:MusicalArtist .
}

SELECT DISTINCT ?sbj WHERE {
    ?sbj dbp:placeOfBirth <A> .
    ?sbj rdf:type dbo:MusicalArtist .
}


############################################################################################
################### QUESTION ANSWERING - DATASET DBNQA #####################################
############################################################################################


ASK WHERE { wd:Q658 wdt:P1108 ?obj filter(?obj < 1.2) }

ask where brack_open wd_q658 wdt_p1108 var_obj 
filter attr_open var_obj math_lt 1_dot_2 attr_close brack_close


ASK WHERE { <sbj_1> wdt:P1108 ?obj filter(?obj < <num>) }

ask where brack_open placeholder_sbj_1 wdt_p1108 var_obj 
filter attr_open var_obj math_lt placeholder_num attr_close brack_close

